# Generated by Django 3.0.7 on 2020-06-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200620_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videofile',
        ),
    ]
