# Generated by Django 3.0.7 on 2020-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200621_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
