# Generated by Django 3.0.7 on 2020-07-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200621_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
    ]
