# Generated by Django 3.0.7 on 2020-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200701_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='post',
            name='videofile',
            field=models.FileField(blank=True, upload_to='media_cdn/%Y/%m/%d/'),
        ),
    ]
